name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash    
        #run: bash test-mariadb.sh
        run: |
          sudo apt-get update; sudo apt-get upgrade -y; 
          sudo apt-get install mariadb-server -y
          sudo service mariadb start
          sudo service mariadb status


     


