name: CI
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: test123
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      run: echo '123'    


     


