# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run S script
        env:
          apple_name: ${{ secrets.AP }}      
        run: |
          git clone https://github.com/Code-Egg/test.git
          sudo bash -x test/test-success.sh ${apple_name}
      - name: Run F script
        run: |
          #sudo bash -x test/test-fail.sh
      - name: echo var1
        run: echo ${{ secrets.NAME }}
      - name: echo var2
        run: echo ${{ secrets.NAME }}        


