# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches:
      - main  
  workflow_dispatch:
env:
  AP: ${{ secrets.AP }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AP: ${{ secrets.AP }}
      ABC: ${{ secrets.ABC_DEF }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          AP: ${{ secrets.AP }} 
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world $AP !  
      - name: Run S script
        env:
          AP: ${{ secrets.AP }}      
        if: env.APP != null  
        run: |
          git clone https://github.com/Code-Egg/test.git
          sudo bash -x test/test-success.sh "$AP"
          echo ${{ job.status }}
      - name: Run F script
        run: |
          #sudo bash -x test/test-fail.sh
      - name: echo var1
        run: echo "$AP $QQ"
        env:
          AP: ${{ secrets.AP }}  
          QQ: 123ddd       
      - name: echo var2
        run: echo "$AP"  
        env:
          AP: ${{ secrets.AP }}      


