name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash    
        #run: bash test-mariadb.sh
        run: |
          sudo apt-get update >/dev/null 2>&1; sudo apt-get upgrade -y >/dev/null 2>&1; 
          sudo echo 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
          sudo apt list --installed | grep -i maria
          sudo echo 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
          sudo apt-get install mariadb-server -y
          #sudo echo 'start----------------'
          #sudo service mariadb start
          #sudo echo 'start----------------'
          sudo service mariadb status


     


